### PR TITLE
feat(ui): replace buttons with icons

### PR DESCRIPTION
**Pull request by MalteRichert**
- improves accessibility since no language/reading is required anymore
- swapping out the icons on click takes a while in testing. that might be improved by caching them

@Rex2002 any opinion on that latter point? I would've done that by reading all icons into a HashMap `<filename, Image>` in `initialize()` but that doesn't feel perfect to me.

### CODE REVIEW

**Comment by Rex2002** [comment]
On my laptop the performance is maybe not good, but I think would be acceptable,
to improve it, maybe we could add some sort of ResourceProvider that loads the images the first time they are needed and caches them afterwards. This would avoid caching unnecessarily many images on startup, but would improve performance (I hope).
Besides that I like the icons, except maybe the metronome-off one, which somehow resembles the deathly-hallows symbol xd (But I have no idea how to make a different metronome-off icon, so probably we can keep that :sweat_smile: )

**Comment by MalteRichert** [comment]
I like the ResourceProvider! Think this might be ready for merge @Rex2002 . Once you approve I'd like to resolve the conflicts since I know the conflicting code well.

**Comment by MalteRichert** [comment]
Also on the icons themselves: We can easily swap out the assets before finishing the project. I wouldn't think of these as final but more as placeholders for the time being.

**Review by Rex2002 — APPROVED** [review]
have a good merge :rocket:

**Pull request merged**
